services:
  workvence-client:
    image: ghcr.io/central-marketing/workvence_client:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workvence_client
    restart: always
    ports:
      - "3500:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
