services:
  workvence-client:
    image: ghcr.io/central-marketing/workvence_client:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_API_URL: https://devadmin.workvence.com/api
        NEXT_PUBLIC_API_URL: https://devadmin.workvence.com/api
        NEXT_PUBLIC_SOCKET_URL: https://devadmin.workvence.com
        NEXT_PUBLIC_ADMIN_API_URL: https://devadmin.workvence.com/api/admin
        NEXT_PUBLIC_ADMIN_BACKEND_URL: https://devadmin.workvence.com
    container_name: workvence_client
    restart: always
    ports:
      - "3500:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_SERVER_API_URL=https://devadmin.workvence.com/api
      - NEXT_PUBLIC_ADMIN_API_URL=https://devadmin.workvence.com/api/admin
    env_file:
      - .env
