version: '3.8'

services:
  workvence-client:
    image: ghcr.io/central-marketing/workvence_client:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workvence_client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Uncomment if using an env file on server
    # env_file:
    #   - .env
